-- tables queries

CREATE TABLE D_ICD_DIAGNOSES (
    ROW_ID INT,
    ICD9_CODE VARCHAR(10) PRIMARY KEY,
    SHORT_TITLE VARCHAR(50),
    LONG_TITLE VARCHAR(300)
);

--

CREATE TABLE PATIENTS (
    ROW_ID INT,
    SUBJECT_ID INT PRIMARY KEY,
    GENDER VARCHAR(5),
    DOB TIMESTAMP(0),
    DOD TIMESTAMP(0),
    DOD_HOSP TIMESTAMP(0),
    DOD_SSN TIMESTAMP(0),
    EXPIRE_FLAG VARCHAR(5)
);


--
CREATE TABLE ADMISSIONS (
    ROW_ID INT,
    SUBJECT_ID INT,
    HADM_ID INT PRIMARY KEY,
    ADMITTIME TIMESTAMP(0),
    DISCHTIME TIMESTAMP(0),
    DEATHTIME TIMESTAMP(0),
    ADMISSION_TYPE VARCHAR(50),
    ADMISSION_LOCATION VARCHAR(50),
    DISCHARGE_LOCATION VARCHAR(50),
    INSURANCE VARCHAR(255),
    LANGUAGE VARCHAR(10),
    RELIGION VARCHAR(50),
    MARITAL_STATUS VARCHAR(50),
    ETHNICITY VARCHAR(200),
    EDREGTIME TIMESTAMP(0),
    EDOUTTIME TIMESTAMP(0),
    DIAGNOSIS VARCHAR(300),
    HOSPITAL_EXPIRE_FLAG SMALLINT,
    HAS_CHARTEVENTS_DATA SMALLINT,
    FOREIGN KEY (SUBJECT_ID) REFERENCES PATIENTS(SUBJECT_ID)
);

--
CREATE TABLE ICUSTAYS (
    ROW_ID INT,
    SUBJECT_ID INT,
    HADM_ID INT,
    ICUSTAY_ID INT PRIMARY KEY,
    DBSOURCE VARCHAR(20),
    FIRST_CAREUNIT VARCHAR(20),
    LAST_CAREUNIT VARCHAR(20),
    FIRST_WARDID SMALLINT,
    LAST_WARDID SMALLINT,
    INTIME TIMESTAMP(0),
    OUTTIME TIMESTAMP(0),
    LOS DOUBLE PRECISION,
    FOREIGN KEY (SUBJECT_ID) REFERENCES PATIENTS(SUBJECT_ID),
    FOREIGN KEY (HADM_ID) REFERENCES ADMISSIONS(HADM_ID)
);

--


CREATE TABLE DIAGNOSES_ICD (
    ROW_ID INT,
    DIAGNOSIS_ID INT PRIMARY KEY,
    SUBJECT_ID INT,
    HADM_ID INT,
    ICD9_CODE VARCHAR(10),
    SEQ_NUM INT,
    DIAGNOSIS_TYPE VARCHAR(50),
    FOREIGN KEY (SUBJECT_ID) REFERENCES PATIENTS(SUBJECT_ID),
    FOREIGN KEY (HADM_ID) REFERENCES ADMISSIONS(HADM_ID),
    FOREIGN KEY (ICD9_CODE) REFERENCES D_ICD_DIAGNOSES(ICD9_CODE)
);

--
CREATE TABLE RADIOLOGY_EXAMS (
    ROW_ID INT,
    EXAM_ID INT PRIMARY KEY,
    SUBJECT_ID INT,
    HADM_ID INT,
    EXAM_TYPE VARCHAR(50),
    BODY_REGION VARCHAR(50),
    EXAM_DATE TIMESTAMP(0),
    EXAM_TIME TIMESTAMP(0),
    ORDERING_PHYSICIAN_ID INT,
    FINDINGS_SUMMARY VARCHAR(300),
    FOREIGN KEY (SUBJECT_ID) REFERENCES PATIENTS(SUBJECT_ID),
    FOREIGN KEY (HADM_ID) REFERENCES ADMISSIONS(HADM_ID)
);

--

CREATE TABLE SURGERIES (
    ROW_ID INT,
    SURGERY_ID INT PRIMARY KEY,
    SUBJECT_ID INT,
    HADM_ID INT,
    SURGERY_TYPE VARCHAR(50),
    PROCEDURE_NAME VARCHAR(100),
    SURGERY_DATE TIMESTAMP(0),
    START_TIME TIMESTAMP(0),
    END_TIME TIMESTAMP(0),
    SURGEON_ID INT,
    URGENCY VARCHAR(20),
    FOREIGN KEY (SUBJECT_ID) REFERENCES PATIENTS(SUBJECT_ID),
    FOREIGN KEY (HADM_ID) REFERENCES ADMISSIONS(HADM_ID)
);

--

CREATE TABLE CLINICAL_NOTES (
    ROW_ID INT,
    NOTE_ID INT PRIMARY KEY,
    SUBJECT_ID INT,
    HADM_ID INT,
    NOTE_TYPE VARCHAR(50),
    NOTE_CATEGORY VARCHAR(50),
    NOTE_DATE TIMESTAMP(0),
    NOTE_TIME TIMESTAMP(0),
    AUTHOR_ID INT,
    AUTHOR_TYPE VARCHAR(50),
    NOTE_TEXT TEXT,
    FOREIGN KEY (SUBJECT_ID) REFERENCES PATIENTS(SUBJECT_ID),
    FOREIGN KEY (HADM_ID) REFERENCES ADMISSIONS(HADM_ID)
);

--

CREATE TABLE PHYSICIAN_VISITS (
    ROW_ID INT,
    VISIT_ID INT PRIMARY KEY,
    SUBJECT_ID INT,
    HADM_ID INT,
    PHYSICIAN_ID INT,
    PHYSICIAN_SPECIALTY VARCHAR(50),
    VISIT_TIME TIMESTAMP(0),
    VISIT_TYPE VARCHAR(50),
    CHIEF_COMPLAINT VARCHAR(300),
    FOREIGN KEY (SUBJECT_ID) REFERENCES PATIENTS(SUBJECT_ID),
    FOREIGN KEY (HADM_ID) REFERENCES ADMISSIONS(HADM_ID)
);

--



