-- Get real ICD9 codes
SELECT ICD9_CODE 
FROM D_ICD_DIAGNOSES;

-- Get all HADM_IDs with their dates
SELECT SUBJECT_ID, HADM_ID, ADMITTIME, DISCHTIME 
FROM ADMISSIONS;

------ INSERT

INSERT INTO DIAGNOSES_ICD (
    ROW_ID, DIAGNOSIS_ID, SUBJECT_ID, HADM_ID, 
    ICD9_CODE, SEQ_NUM, DIAGNOSIS_TYPE)
SELECT 
    ROW_NUMBER() OVER() as ROW_ID,
    ROW_NUMBER() OVER() as DIAGNOSIS_ID,
    a.SUBJECT_ID,
    a.HADM_ID,
    d.ICD9_CODE,
    SEQ_NUM,
    CASE WHEN SEQ_NUM = 1 THEN 'Admitting'
         WHEN SEQ_NUM = 2 THEN 'Discharge'
         ELSE 'Complication' END as DIAGNOSIS_TYPE
FROM ADMISSIONS a
CROSS JOIN LATERAL (
    SELECT ICD9_CODE 
    FROM D_ICD_DIAGNOSES 
    ORDER BY RANDOM() 
    LIMIT 3
) d
CROSS JOIN LATERAL (
    SELECT generate_series AS SEQ_NUM 
    FROM generate_series(1, 3)
) s
LIMIT 2000;

-- to test
SELECT COUNT(*) FROM DIAGNOSES_ICD;
SELECT * FROM DIAGNOSES_ICD LIMIT 10;