INSERT INTO RADIOLOGY_EXAMS (
    ROW_ID, EXAM_ID, SUBJECT_ID, HADM_ID,
    EXAM_TYPE, BODY_REGION, EXAM_DATE,
    EXAM_TIME, ORDERING_PHYSICIAN_ID, FINDINGS_SUMMARY)
SELECT
    ROW_NUMBER() OVER() as ROW_ID,
    ROW_NUMBER() OVER() as EXAM_ID,
    SUBJECT_ID,
    HADM_ID,
    CASE WHEN ROW_NUMBER() OVER() % 4 = 0 THEN 'X-Ray'
         WHEN ROW_NUMBER() OVER() % 4 = 1 THEN 'CT'
         WHEN ROW_NUMBER() OVER() % 4 = 2 THEN 'MRI'
         ELSE 'Ultrasound' END as EXAM_TYPE,
    CASE WHEN ROW_NUMBER() OVER() % 3 = 0 THEN 'Chest'
         WHEN ROW_NUMBER() OVER() % 3 = 1 THEN 'Abdomen'
         ELSE 'Head' END as BODY_REGION,
    ADMITTIME + (RANDOM() * (DISCHTIME - ADMITTIME)) as EXAM_DATE,
    ADMITTIME + (RANDOM() * (DISCHTIME - ADMITTIME)) as EXAM_TIME,
    FLOOR(RANDOM() * 100 + 1)::INT as ORDERING_PHYSICIAN_ID,
    CASE WHEN ROW_NUMBER() OVER() % 3 = 0 THEN 'Normal findings'
         WHEN ROW_NUMBER() OVER() % 3 = 1 THEN 'Abnormal findings'
         ELSE 'Recovery progress noted' END as FINDINGS_SUMMARY
FROM ADMISSIONS
WHERE DISCHTIME IS NOT NULL
LIMIT 500;

-- test
SELECT COUNT(*) FROM RADIOLOGY_EXAMS;
SELECT * FROM RADIOLOGY_EXAMS LIMIT 10;